import type { AssetMeta, AssetType } from "@/types";

export const ASSETS: Record<AssetType, AssetMeta> = {
  premium_product_photo: {
    id: "premium_product_photo",
    label: "Premium Product Photo",
    description: "Hero studio shot, catalog-grade.",
    orientation: "square",
    aspect: "1:1",
    pixelHint: "2048x2048",
    platform: "Catalog",
  },
  ecommerce_thumbnail: {
    id: "ecommerce_thumbnail",
    label: "Ecommerce Thumbnail",
    description: "Clean white-ish thumb for marketplace listings.",
    orientation: "square",
    aspect: "1:1",
    pixelHint: "1200x1200",
    platform: "Shopify / Etsy",
  },
  instagram_post: {
    id: "instagram_post",
    label: "Instagram Post",
    description: "Square feed-ready editorial photo.",
    orientation: "square",
    aspect: "1:1",
    pixelHint: "1080x1080",
    platform: "Instagram",
  },
  instagram_story: {
    id: "instagram_story",
    label: "Instagram Story",
    description: "Vertical 9:16 with breathing room for text.",
    orientation: "portrait",
    aspect: "9:16",
    pixelHint: "1080x1920",
    platform: "Instagram",
  },
  pinterest_pin: {
    id: "pinterest_pin",
    label: "Pinterest Pin",
    description: "Tall 2:3 lifestyle flatlay, viral-ready.",
    orientation: "portrait",
    aspect: "2:3",
    pixelHint: "1000x1500",
    platform: "Pinterest",
  },
  shopee_cover: {
    id: "shopee_cover",
    label: "Shopee / Tokopedia Cover",
    description: "SEA marketplace hero cover, vibrant clean.",
    orientation: "square",
    aspect: "1:1",
    pixelHint: "1024x1024",
    platform: "Shopee / Tokopedia",
  },
  whatsapp_catalog: {
    id: "whatsapp_catalog",
    label: "WhatsApp Catalog",
    description: "Mobile-first square product card.",
    orientation: "square",
    aspect: "1:1",
    pixelHint: "1080x1080",
    platform: "WhatsApp Business",
  },
  lifestyle_mockup: {
    id: "lifestyle_mockup",
    label: "Lifestyle Mockup",
    description: "Product in real human / child context.",
    orientation: "landscape",
    aspect: "3:2",
    pixelHint: "1800x1200",
    platform: "Lifestyle",
  },
  packaging_preview: {
    id: "packaging_preview",
    label: "Packaging Preview",
    description: "Product packaged / boxed catalog shot.",
    orientation: "square",
    aspect: "1:1",
    pixelHint: "1500x1500",
    platform: "Brand",
  },
  ad_creative: {
    id: "ad_creative",
    label: "Ad Creative",
    description: "Conversion-tuned vertical or square ad image.",
    orientation: "portrait",
    aspect: "4:5",
    pixelHint: "1080x1350",
    platform: "Meta Ads",
  },
};

export const ASSET_LIST: AssetMeta[] = Object.values(ASSETS);
